#!/bin/bash
your_qt_path='/usr/local/Trolltech/Qt-4.8.7'
your_qwt_path='/usr/local/qwt-6.1.2'


################################################
#create directory with correct architecture

rm -rf dmg_contents
rm pack.temp.dmg

mkdir dmg_contents
mkdir dmg_contents/Aseba
cd dmg_contents/Aseba
mkdir libraries
mkdir bin
mkdir .background

for asebaapps in "Aseba Playground.app" "Aseba Challenge.app" "Aseba Studio.app" "Thymio Firmware Upgrader.app" "Aseba Studio for Thymio.app" "Thymio VPL.app"
do
	mkdir -p "$asebaapps/Contents/"{MacOS,Plugins/{imageformats,sqldrivers,iconengines},Resources,Frameworks}
	cp $WORKSPACE/source/packager/Resources/qt.conf "$asebaapps/Contents/Resources/"
done

#copy resources into bundle folders
cp $WORKSPACE/source/aseba/targets/playground/unifr.playground .
cp $WORKSPACE/source/aseba/menu/osx/asebachallenge.icns Aseba\ Challenge.app/Contents/Resources
cp $WORKSPACE/source/packager/Resources/Info.plist.challenge Aseba\ Challenge.app/Contents/Info.plist
cp $WORKSPACE/source/aseba/menu/osx/thymioupgrader.icns Thymio\ Firmware\ Upgrader.app/Contents/Resources
cp $WORKSPACE/source/packager/Resources/Info.plist.flasher Thymio\ Firmware\ Upgrader.app/Contents/Info.plist
cp $WORKSPACE/source/aseba/menu/osx/asebastudio.icns Aseba\ Studio.app/Contents/Resources
cp $WORKSPACE/source/packager/Resources/Info.plist.studio Aseba\ Studio.app/Contents/Info.plist
cp $WORKSPACE/source/aseba/menu/osx/asebaplayground.icns Aseba\ Playground.app/Contents/Resources
cp $WORKSPACE/source/packager/Resources/Info.plist.playground Aseba\ Playground.app/Contents/Info.plist
cp $WORKSPACE/source/aseba/menu/osx/asebastudiothymio.icns Aseba\ Studio\ for\ Thymio.app/Contents/Resources
cp $WORKSPACE/source/packager/Resources/Info.plist.asethym Aseba\ Studio\ for\ Thymio.app/Contents/Info.plist
cp $WORKSPACE/source/aseba/menu/osx/thymiovpl.icns Thymio\ VPL.app/Contents/Resources
cp $WORKSPACE/source/packager/Resources/Info.plist.vpl Thymio\ VPL.app/Contents/Info.plist

#copy all necessary libraries, plugins etc in the package and make them link to the right places
cd libraries

for qtlib in "QtGui" "QtCore" "QtOpenGL" "QtXml" "QtNetwork" "QtHelp" "QtSql" "QtSvg"
do
	cp -R $your_qt_path/lib/$qtlib.framework .
	rm $qtlib.framework/Versions/4/*_debug
	rm $qtlib.framework/Versions/Current/*_debug
	rm $qtlib.framework/*_debug
	rm $qtlib.framework/*_debug.prl

	install_name_tool -change $your_qt_path/lib/QtSql.framework/Versions/4/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/4/QtSql $qtlib.framework/Versions/4/$qtlib
	install_name_tool -change $your_qt_path/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui $qtlib.framework/Versions/4/$qtlib
	install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore $qtlib.framework/Versions/4/$qtlib 
	install_name_tool -change $your_qt_path/lib/QtXml.framework/Versions/4/QtXml @executable_path/../Frameworks/QtXml.framework/Versions/4/QtXml $qtlib.framework/Versions/4/$qtlib 
	install_name_tool -change $your_qt_path/lib/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../Frameworks/QtNetwork.framework/Versions/4/QtNetwork $qtlib.framework/Versions/4/$qtlib 
	install_name_tool -change $your_qt_path/lib/QtOpenGL.framework/Versions/4/QtOpenGL @executable_path/../Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL $qtlib.framework/Versions/4/$qtlib 
	install_name_tool -change $your_qt_path/lib/libz.1.2.3.dylib @executable_path/../Frameworks/libz.1.2.3.dylib $qtlib.framework/Versions/4/$qtlib
	install_name_tool -change $your_qt_path/lib/libQtCLucene.4.dylib @executable_path/../Frameworks/libQtCLucene.4.8.7.dylib $qtlib.framework/Versions/4/$qtlib
	install_name_tool -id  @executable_path/../Frameworks/$qtlib.framework/Versions/4/$qtlib $qtlib.framework/Versions/4/$qtlib
	otool -L $qtlib.framework/Versions/4/$qtlib 
done


cp $your_qwt_path/lib/libqwt.6.1.2.dylib .
install_name_tool -id  @executable_path/../Frameworks/libqwt.6.1.2.dylib libqwt.6.1.2.dylib
install_name_tool -change $your_qt_path/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui libqwt.6.1.2.dylib
install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore libqwt.6.1.2.dylib
install_name_tool -change $your_qt_path/lib/QtSvg.framework/Versions/4/QtSvg @executable_path/../Frameworks/QtSvg.framework/Versions/4/QtSvg libqwt.6.1.2.dylib
otool -L libqwt.6.1.2.dylib


cp $WORKSPACE/build/dashel/libdashel.1.1.0.dylib .
install_name_tool -id  @executable_path/../Frameworks/libdashel.1.1.0.dylib libdashel.1.1.0.dylib
otool -L libdashel.1.1.0.dylib


cp $your_qt_path/lib/libQtCLucene.4.8.7.dylib .
install_name_tool -id @executable_path/../Frameworks/libQtCLucene.4.8.7.dylib libQtCLucene.4.8.7.dylib
install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore libQtCLucene.4.8.7.dylib
otool -L libQtCLucene.4.8.7.dylib

cp $your_qt_path/plugins/sqldrivers/libqsqlite.dylib .
install_name_tool -id @executable_path/../Plugins/sqldrivers/libraries/libqsqlite.dylib libqsqlite.dylib 
install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore libqsqlite.dylib
install_name_tool -change $your_qt_path/lib/QtSql.framework/Versions/4/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/4/QtSql libqsqlite.dylib
otool -L libqsqlite.dylib

for formatplugin in "libqgif" "libqico" "libqjpeg" "libqmng" "libqsvg" "libqtga" "libqtiff"
do
	cp $your_qt_path/plugins/imageformats/$formatplugin.dylib .
	install_name_tool -id @executable_path/../Plugins/imageformats/$formatplugin.dylib $formatplugin.dylib 
	install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore $formatplugin.dylib
	install_name_tool -change $your_qt_path/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui $formatplugin.dylib
	install_name_tool -change $your_qt_path/lib/QtSql.framework/Versions/4/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/4/QtSql $formatplugin.dylib
	install_name_tool -change $your_qt_path/lib/QtXml.framework/Versions/4/QtXml @executable_path/../Frameworks/QtXml.framework/Versions/4/QtXml $formatplugin.dylib
	install_name_tool -change $your_qt_path/lib/QtSvg.framework/Versions/4/QtSvg @executable_path/../Frameworks/QtSvg.framework/Versions/4/QtSvg $formatplugin.dylib
	otool -L $formatplugin.dylib
done


cp $your_qt_path/plugins/iconengines/libqsvgicon.dylib .
install_name_tool -id @executable_path/../Plugins/iconengines/libqsvgicon.dylib libqsvgicon.dylib 
install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore libqsvgicon.dylib
install_name_tool -change $your_qt_path/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui libqsvgicon.dylib
install_name_tool -change $your_qt_path/lib/QtXml.framework/Versions/4/QtXml @executable_path/../Frameworks/QtXml.framework/Versions/4/QtXml libqsvgicon.dylib
install_name_tool -change $your_qt_path/lib/QtSvg.framework/Versions/4/QtSvg @executable_path/../Frameworks/QtSvg.framework/Versions/4/QtSvg libqsvgicon.dylib
otool -L libqsvgicon.dylib

cd ..


#copy all executables 

cp $WORKSPACE/build/aseba/clients/cmd/asebacmd .
cp $WORKSPACE/build/aseba/clients/dump/asebadump .
cp $WORKSPACE/build/aseba/clients/replay/asebaplay .
cp $WORKSPACE/build/aseba/clients/replay/asebarec .
cp $WORKSPACE/build/aseba/clients/massloader/asebamassloader .
cp $WORKSPACE/build/aseba/switches/switch/asebaswitch .
cp $WORKSPACE/build/aseba/switches/http/asebahttp .
cp $WORKSPACE/build/aseba/targets/dummy/asebadummynode .
cp $WORKSPACE/build/aseba/clients/studio/asebastudio .
cp $WORKSPACE/build/aseba/clients/studio/thymiovpl .
cp $WORKSPACE/build/aseba/targets/challenge/asebachallenge .
cp $WORKSPACE/build/aseba/targets/playground/asebaplayground .
cp $WORKSPACE/build/aseba/clients/thymioupgrader/thymioupgrader .


#make them link to the correct libraries
for asebaexec in "asebachallenge" "asebastudio" "asebaplayground" "thymioupgrader" "thymiovpl" 
do
	install_name_tool -change $your_qt_path/lib/QtHelp.framework/Versions/4/QtHelp @executable_path/../Frameworks/QtHelp.framework/Versions/4/QtHelp $asebaexec
	install_name_tool -change $your_qt_path/lib/QtSql.framework/Versions/4/QtSql @executable_path/../Frameworks/QtSql.framework/Versions/4/QtSql $asebaexec
	install_name_tool -change $your_qt_path/lib/QtGui.framework/Versions/4/QtGui @executable_path/../Frameworks/QtGui.framework/Versions/4/QtGui $asebaexec
	install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../Frameworks/QtCore.framework/Versions/4/QtCore $asebaexec 
	install_name_tool -change $your_qt_path/lib/QtXml.framework/Versions/4/QtXml @executable_path/../Frameworks/QtXml.framework/Versions/4/QtXml $asebaexec 
	install_name_tool -change $your_qt_path/lib/QtNetwork.framework/Versions/4/QtNetwork @executable_path/../Frameworks/QtNetwork.framework/Versions/4/QtNetwork $asebaexec 
	install_name_tool -change $your_qt_path/lib/QtOpenGL.framework/Versions/4/QtOpenGL @executable_path/../Frameworks/QtOpenGL.framework/Versions/4/QtOpenGL $asebaexec
	install_name_tool -change $your_qt_path/lib/QtSvg.framework/Versions/4/QtSvg @executable_path/../Frameworks/QtSvg.framework/Versions/4/QtSvg $asebaexec
	install_name_tool -change $your_qwt_path/lib/libqwt.6.1.2.dylib @executable_path/../Frameworks/libqwt.6.1.2.dylib $asebaexec
	install_name_tool -change $WORKSPACE/build/dashel/libdashel.1.dylib @executable_path/../Frameworks/libdashel.1.1.0.dylib $asebaexec
    otool -L $asebaexec
done


mv asebastudio Aseba\ Studio.app/Contents/MacOS/
mv asebachallenge Aseba\ Challenge.app/Contents/MacOS/
mv asebaplayground Aseba\ Playground.app/Contents/MacOS/
mv thymioupgrader Thymio\ Firmware\ Upgrader.app/Contents/MacOS/
cp $WORKSPACE/source/packager/Resources/asethym Aseba\ Studio\ for\ Thymio.app/contents/MacOS/
mv thymiovpl Thymio\ VPL.app/Contents/MacOS/
cp $WORKSPACE/source/packager/Resources/launchthymiovpl Thymio\ VPL.app/contents/MacOS/

mkdir Simulations
#create symlinks to the libraries
for asebaapps in "Aseba Playground.app" "Aseba Challenge.app" "Aseba Studio.app" "Thymio Firmware Upgrader.app" "Aseba Studio for Thymio.app" "Thymio VPL.app"
do
	cd "$asebaapps/Contents/Frameworks/"
	for qtframework in "QtGui" "QtCore" "QtOpenGL" "QtXml" "QtNetwork" "QtHelp" "QtSql" "QtSvg"
	do
		ln -s ../../../libraries/$qtframework.framework
	done

	ln -s ../../../libraries/libqwt.6.1.2.dylib
	ln -s ../../../libraries/libdashel.1.1.0.dylib
	ln -s ../../../libraries/libQtCLucene.4.8.7.dylib

	cd ../Plugins/imageformats
	for qtplugin in "libqgif.dylib" "libqico.dylib" "libqjpeg.dylib" "libqmng.dylib" "libqsvg.dylib" "libqtga.dylib" "libqtiff.dylib"
	do
		ln -s ../../../../libraries/$qtplugin .
	done

	cd ../iconengines
	ln -s ../../../../libraries/libqsvgicon.dylib .

	cd ../sqldrivers
	ln -s ../../../../libraries/libqsqlite.dylib .
	cd ../../../.. 
done

#take care of executables that are not in an app bundle = those that will be used rather in command line and do not need a nice icon
for asebaexec in "asebaswitch" "asebarec" "asebacmd" "asebadump" "asebaplay" "asebadummynode" "asebahttp" "asebamassloader"
do
	install_name_tool -change $WORKSPACE/build/dashel/libdashel.1.dylib @executable_path/../libraries/libdashel.1.1.0.dylib $asebaexec
	install_name_tool -change $your_qt_path/lib/QtCore.framework/Versions/4/QtCore @executable_path/../libraries/QtCore.framework/Versions/4/QtCore $asebaexec
	install_name_tool -change $your_qt_path/lib/QtXml.framework/Versions/4/QtXml @executable_path/../libraries/QtXml.framework/Versions/4/QtXml $asebaexec
	otool -L $asebaexec
done



mv asebacmd bin/
mv asebadump bin/
mv asebaplay bin/
mv asebarec bin/
mv asebaswitch bin/
mv asebadummynode bin/
mv asebahttp bin/
mv asebamassloader bin/

cd ../..

hdiutil create -srcfolder "dmg_contents" -volname "Aseba" -fs HFS+ \
      -fsargs "-c c=64,a=16,e=16" -format UDRW -size $200000k aseba.dmg
      
echo '
   tell application "Finder"
     tell disk "'aseba.dmg'"
           open
           set current view of container window to icon view
           set toolbar visible of container window to false
           set statusbar visible of container window to false
           set the bounds of container window to {400, 100, 885, 430}
           set theViewOptions to the icon view options of container window
           set arrangement of theViewOptions to not arranged
           set icon size of theViewOptions to 72
           set background picture of theViewOptions to file ".background:'background.png'"
           make new alias file at container window to POSIX file "/Applications" with properties {name:"Applications"}
           set position of item "'Aseba'" of container window to {100, 100}
           set position of item "Applications" of container window to {375, 100}
           update without registering applications
           delay 5
           close
     end tell
   end tell
' | osascript
